// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDByBobPL23uxm7Rq3a3CYqpsVUtIwZmao',
    appId: '1:90992896817:web:1d753a0ee94d9ecada9e10',
    messagingSenderId: '90992896817',
    projectId: 'reddit-clone-19d4c',
    authDomain: 'reddit-clone-19d4c.firebaseapp.com',
    storageBucket: 'reddit-clone-19d4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRTmAhwBkjILIMwedGWCdYKhznctw_3o',
    appId: '1:90992896817:android:e0bcf8e7262fd9fcda9e10',
    messagingSenderId: '90992896817',
    projectId: 'reddit-clone-19d4c',
    storageBucket: 'reddit-clone-19d4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0x3R2OVxZCWyjDszMKfOrsDZlS06aPU',
    appId: '1:90992896817:ios:5a2fae4fb8e5b080da9e10',
    messagingSenderId: '90992896817',
    projectId: 'reddit-clone-19d4c',
    storageBucket: 'reddit-clone-19d4c.appspot.com',
    iosClientId: '90992896817-u250hjuch4d0c3k9sarpp691h1bpoca7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
